require('mappings')
require('plugins')
require('config')

require('aram.lsp')
require('aram.autocomplete')
require('aram.autobrackets')
require('aram.statusbar')
require('aram.treesitter')
require('aram.lspsaga')
require('aram.telescope')
require('aram.luasnip')
require('aram.cmp')
require('aram.gitsigns')
require('aram.nvimtree')
require('aram.hop')
